# Generated by Django 3.2.18 on 2023-11-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='tb_content',
        ),
    ]
