# Generated by Django 3.2.18 on 2023-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=20, verbose_name='图片名称')),
                ('image_data', models.BinaryField(max_length=256, verbose_name='二进制图片')),
            ],
            options={
                'verbose_name': '二进制图片',
                'verbose_name_plural': '二进制图片',
                'db_table': 'tb_image_data',
            },
        ),
    ]
