# Generated by Django 3.2.18 on 2023-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_imagestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='image_data',
            field=models.BinaryField(default=None, max_length=256, verbose_name='二进制图片'),
        ),
    ]
