# Generated by Django 3.2.18 on 2023-11-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_imagestorage_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='image_data',
            field=models.BinaryField(max_length=256, null=True, verbose_name='二进制图片'),
        ),
    ]
