# Generated by Django 3.2.18 on 2023-12-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_goodsvisitcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsvisitcount',
            old_name='count',
            new_name='counts',
        ),
    ]
